### ISSUE TITLE
Detail out menu heirarchy

### ISSUE THREAD

**Issue by NoahYB** [NoahYB/FPSThreeJS#10]
Servers -> Server List -> Join Game
About -> github
Donate -> venmo

**Comment by Rocky760** [comment]
START {with background}
L>Servers
|....L> 1. High Pass
|...........2. Oasis
|............3. Forest
|.............4. Station
L>Donate
|....L> Gethub
|...........Venmo
|...........Cashapp
L>About
|.......> Small bio or joke in plain text with easteregg html link hidden on page/credit to software used
L>Contact
|.....L> support@domain.com address, or pull like that other guy who does domain hosting does and give out personal 
|............email/phone number
L>Exit/Reset
|.......L> hyperlink to either boot them to google or something funny/or a manual page refresh

**Comment by Rocky760** [comment]
Here are images for map previews. Made these myself, so all seems to be fair use.

![High Pass](https://user-images.githubusercontent.com/8892828/202079898-9a38d3a6-d6dc-49fa-8c97-d77ff2293da9.png)

![Oasis](https://user-images.githubusercontent.com/8892828/202079902-4753dbc6-5068-41ca-a95a-6b7ce63e9a12.png)

![Forrest](https://user-images.githubusercontent.com/8892828/202079889-aaa04265-3931-4855-a131-930406d32369.png)

![Station](https://user-images.githubusercontent.com/8892828/202079910-ea64540e-940c-4d3c-9ec8-3cc4028a794c.png)

**Comment by Rocky760** [comment]
We can see how they fit and look, can always trim them all too look like forest

**Comment by Rocky760** [comment]
Ideally we could have 5 servers for each map but. We have to even make different maps first.

**Comment by NoahYB** [comment]
Yo those look awesome

**Comment by NoahYB** [comment]
Love it
