### ISSUE TITLE
[SIMPLE FIX?] | Jump reset on ground

### ISSUE THREAD

**Issue by Rocky760** [NoahYB/FPSThreeJS#16]
Two ways I can picture this being done - 

Have the "jump" ability reset upon contact between some measured/checkl point on the player and where the player connects with the map (using some node at the bottom of the hitbox).

OR

Just make jump reset after a timer greater than or equal to the time of the full jump animation. Seems to be just under a minute at around 0.50 seconds for the whole animation/trajectory to take place | Tested with (.008)=gravity and 30=Jumpheight. Maybe putting the timer at 1 second would be a sweet spot idk. 

The only issue I see is when falling, you would have a second jump if your fall lasted longer than 1 second. But also maybe a little air hop is tight.

The nice thing is that either way, its not affected by movement speed.

**Comment by NoahYB** [comment]
Going to tackle this one,
Probably make a toggle for both so we can test it

**Comment by NoahYB** [comment]
Actually will just do the easier one reset when touching the ground

can revisit later

**Comment by NoahYB** [comment]
Closed with branch 16
